### ISSUE TITLE
Best practice to reuse parametric selectors

### ISSUE THREAD

**Issue by martinkutter** [josepot/redux-views#28]
What is the best practice to reuse the `getMediaAssetForShape` selector in the following example?

```js
const getCarShapeFromProps = createIdSelector(props => props.shape);
const getMediaAssetForShape = createSelector(
  [
    getCarShapeFromProps,
    getConvertibleMediaAsset,
    getStationWagonMediaAsset
  ],
  (shape, convertibleMediaAsset, stationWagonMediaAsset) => 
    shape === "convertible" ? convertibleMediaAsset : stationWagonMediaAsset
);

const getLeftCarMediaAsset = createSelector(
  [getLeftPlayerCarShape],
  (shape) => // reuse getMediaAssetForShape with shape as prop
);
const getRightCarMediaAsset = createSelector(
  [getRightPlayerCarShape],
  (shape) => // reuse getMediaAssetForShape with shape as prop
);
```

**Comment by josepot** [comment]
Sorry, but I don't understand the question. Could please explain a bit better what it is that you are trying to do?

I guess that I must be missing something, but if what you need is to create a selector that depends on `getMediaAssetForShape`, then put it in the list of dependencies of the next selector and that's it.

**Comment by martinkutter** [comment]
Hey @josepot,

in this basic example `getMediaAssetForShape` is a parametric selector based on the prop `shape`. So I can not reuse it as dependency of `getLeftCarMediaAsset`, because there is no `shape` prop. The correct shape in this case comes from `getLeftPlayerCarShape`.

A possible solution could be:
```
const getCarShapeFromProps = createIdSelector(props => props.shape);

const getMediaAssetForShapeCombiner = (shape, convertibleMediaAsset, stationWagonMediaAsset) => 
    shape === "convertible" ? convertibleMediaAsset : stationWagonMediaAsset;

const getMediaAssetForShape = createSelector(
  [
    getCarShapeFromProps,
    getConvertibleMediaAsset,
    getStationWagonMediaAsset
  ],
  getMediaAssetForShapeCombiner
);

const getLeftCarMediaAsset = createSelector(
  [getLeftPlayerCarShape, getConvertibleMediaAsset, getStationWagonMediaAsset],
  getMediaAssetForShapeCombiner
);
const getRightCarMediaAsset = createSelector(
  [getRightPlayerCarShape, getConvertibleMediaAsset, getStationWagonMediaAsset],
  getMediaAssetForShapeCombiner
);
```

But in this case, there is no common cache like for a parametric selector and much boilerplate.

**Comment by josepot** [comment]
This could be an "issue" with the way that you are modeling your selectors, I'm not sure, because I still think that I don't have enough context. However, maybe this helps?

```js
const getCarShapeFromProps = createIdSelector(props => props.shape);
const identity = x => x;

const getMediaAssetForShape = createSelector(
  [
    getCarShapeFromProps,
    getConvertibleMediaAsset,
    getStationWagonMediaAsset
  ],
  (shape, convertibleMediaAsset, stationWagonMediaAsset) => 
    shape === "convertible" ? convertibleMediaAsset : stationWagonMediaAsset
);

const getSide = createIdSelector(props => props.side)

const getSideShape = createSelector(
  [getSide, getLeftPlayerCarShape, getRightPlayerCarShape, ],
  (side, left, right) => ({ shape: side === 'left' ? left : right })
)

const getCarMediaAsset = createSelector(
  [identity, getSideShape],
  getMediaAssetForShape
);

// getCarMediaAsset(state, {side: 'left'})
// getCarMediaAsset(state, {side: 'right'})
```

> But in this case, there is no common cache like for a parametric selector

I think that this should address the issue with the caches?

>  and much boilerplate.

If you don't like boilerplate, then you should really consider to stop using Redux :wink:

**Comment by martinkutter** [comment]
Yes, that was what I was looking for. 
If I understand correct, in this case the `x` in `const identity = x => x` is of type `AppState` (type of redux state)?
May I ask why you choose the name `identity` and what would a test for your `getCarMediaAsset` selector would look like?

**Comment by josepot** [comment]
> Yes, that was what I was looking for.

:tada: 

> If I understand correct, in this case the `x` in `const identity = x => x` is of type `AppState` (type of redux state)?

yes, that is correct.

> May I ask why you choose the name `identity`?

Because that's [the name that it receives in math](https://en.wikipedia.org/wiki/Identity_function), and it's a common concept in functional programming. Also, there are many libraries that expose the `identity` function: ramda, rxjs, lodash, etc.

Just to be clear, though. These kind of selectors:

```js
const getMediaAssetForShape = createSelector(
  [
    getCarShapeFromProps,
    getConvertibleMediaAsset,
    getStationWagonMediaAsset
  ],
  (shape, convertibleMediaAsset, stationWagonMediaAsset) => 
    shape === "convertible" ? convertibleMediaAsset : stationWagonMediaAsset
);
```

can be problematic, because both `getConvertibleMediaAsset` and `getStationWagonMediaAsset` will be evaluated regardless of what `shape` returns... IMO that's quite unfortunate, because for instance imagine that shape hasn't changed, but the selector that computes the value that it's being ignored changes... Then, that selector gets evaluated anyways, when in reality that value is not being used, which I find very annoying :roll_eyes:. A few weeks before I gave up on Redux I was about to add a new function named `createSwitchSelector`, the idea was that there was a selector that returned the key of the selector that was meant to be evaluated, which guaranteed that no unnecessary computations were going to take place.

However, I ended up realizing that the only reason why I was having all these issues was because I was using a state-management library that treated my state as a black-box and that wasn't able to understand how the different parts of the state related with each other. So, I gave up on Redux and I ended up [creating a set of bindings for rxjs](https://github.com/re-rxjs/react-rxjs) and now I'm in heaven :smile:.
