### ISSUE TITLE
Readme Sample Incorrect and Incomplete

### ISSUE THREAD

**Issue by Domiii** [josepot/redux-views#31]
I was surprised to read the last line of the first sample implying `getRunningCars` was computed more than once: 

```js
assert(getRunningCars.recomputations() === 2); // turns out, it should be `getRunningCar` (not `getRunningCars`)
```

I tried to run it myself and found that the sample is incomplete and buggy.

Here is a complete and corrected version:

```js
/**
 * @file 
 * @see https://github.com/josepot/redux-views
 */

const { createSelector, createIdSelector } = require('redux-views');

const state = {
  cars: [
    {
      id: 1,
      isRunning: true,
      passengerIds: ['p1', 'p3']
    },
    {
      id: 2,
      isRunning: true,
      passengerIds: ['p2', 'p4', 'p5']
    }
  ],
  people: {
    p1: {},
    p2: {},
    p3: {},
    p4: {},
    p5: {}
  }
}

const getAllCars = state => state.cars;
const getAllPeople = state => state.people;

const getRunningCars = createSelector(
  [getAllCars],
  cars => cars.filter(car => car.isRunning)
);
const getCarIdProp = createIdSelector(props => props.carId);
const getRunningCar = createSelector(
  [
    getRunningCars,
    getCarIdProp
  ],
  (cars, carId) => cars.find(car => car.id === carId)
);
const getRunningCarPassengers = createSelector(
  [
    getRunningCar,
    getAllPeople
  ],
  (car, people) => car.passengerIds.map(id => people[id])
);

console.log('running car #1:', getRunningCar(state, { carId: 1 }));

const passengersCar1_0 = getRunningCarPassengers(state, { carId: 1 }); // computes
const passengersCar2 = getRunningCarPassengers(state, { carId: 2 }); // computes
const passengersCar1_1 = getRunningCarPassengers(state, { carId: 1 }); // cached

console.assert(passengersCar1_0 === passengersCar1_1);
console.assert(getRunningCars.recomputations() === 1);
console.assert(getRunningCar.recomputations() === 2);
```

**Comment by voliva** [comment]
Thanks for raising this issue.

It's right that there's a typo on the assertion you point out on the Readme: instead of `getRunningCars` it should be `getRunningCar`.

That section is explaining how redux-views manages parametric selectors, and `getRunningCar` is the parametric selector that is being tested. Somehow that "s" slipped in. Do you want to raise a PR for it? Otherwise someone else can take it.

I would like to point out that I don't think the explaination on the Readme is meant to be a working example, but it just wants to explain what's the point of this library and how it differs to reselect v4.

I personally wouldn't try to make it "complete" by adding in a specific state definition and every single selector needed for this to run, as I feel like it would just add noise.

**Comment by Domiii** [comment]
> I personally wouldn't try to make it "complete" by adding in a specific state definition and every single selector needed for this to run, as I feel like it would just add noise.

@voliva I agree with that notion. In that case, I would still strongly suggest to add working examples to the repository and link it up then. All the big APIs have tons of working examples, that you can just point to and run; and it makes things a lot easier. Also, only once you have it working, you can make sure that these types of bugs won't end up on your front page! :P


### Somewhat off-topic

I found the lack of samples to play around with to be a major overhead to get into this (or similar) libraries, despite being so easy to use. Having to reason about, correct and/or event write my own samples to make sure that I get everything right, could take 10 minutes for some and 2 hours for others... That "onboarding difficulty" might contribute to the low visibility of big/important ideas and libraries like this one right here :/
